CREATE TABLE website_data (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT,
    name TEXT,
    source_type TEXT,
    title TEXT,
    url TEXT,
    added_date TIMESTAMP,
    latest_date TIMESTAMP,
    company TEXT,
    location TEXT,
    country TEXT[],
    job_type TEXT[],
    data_status TEXT
);

CREATE TABLE brand_data (
    id TEXT,
    name TEXT,
    image TEXT,
    brand_type TEXT[]
);